# Todo: Load the paths as dotenv var (see MLHD project)

# Model Settings
args:
  EMBEDDING_MODEL_NAME: "C:/Users/aliin/.cache/huggingface/hub/models--intfloat--multilingual-e5-large-instruct/snapshots/274baa43b0e13e37fafa6428dbc7938e62e5c439" # 'intfloat/multilingual-e5-large-instruct' ## "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
  MAX_EMBED_TOKENS: 512      ## SentenceTransformer(EMBEDDING_MODEL_NAME).max_seq_length

  RERANKER_MODEL: "C:/Users/aliin/.cache/huggingface/hub/models--BAAI--bge-reranker-v2-m3/snapshots/953dc6f6f85a1b2dbfca4c34a2796e7dde08d41e" # "BAAI/bge-reranker-v2-m3"  ## HuggingFace model for re-ranking
  PRUNER_MODEL: "C:/Users/aliin/.cache/huggingface/hub/models--naver--xprovence-reranker-bgem3-v1/snapshots/8dd5d79b6b57b3498a1180352daaf8c457af832b" # "naver/xprovence-reranker-bgem3-v1" # path to snapshots/hashfile

  OLLAMA_HOST: "http://localhost:11434"
  LLM_MODEL: "gemma3:4b" ## Any model from Ollama [gemma3:4b, ministral-3:3b-instruct-2512-q4_K_M, llama3.2:3b-instruct-q8_0, llama3.2:3b-instruct-q4_K_M, qwen3.5:4b]
  EVALUATOR_LLM: "mistral:7b-instruct" ## in ["gemma3:4b", "mistral:7b-instruct", qwen3.5:4b]
  EXTRACTOR_LLM: "gemma3:4b" # ["ministral-3:3b-instruct-2512-q4_K_M", "llama3.2:3b-instruct-q4_K_M", "gemma3:4b", "qwen3.5:4b"]
  
  CHUNKS_TYPE: "custom_chunks"         ## one of: "custom_chunks", "fixed_size_chunks", "semantic_chunks"




  # EMBEDDING_MODEL_NAME: "intfloat/multilingual-e5-large-instruct"   # Loaded from .env for path
  # RERANKER_MODEL: "BAAI/bge-reranker-v2-m3"                         # Loaded from .env for path
  # PRUNER_MODEL: "naver/xprovence-reranker-bgem3-v1"                 # Loaded from .env for path
  # BASE_DIR: ${BASE_DIR}                                             # Loaded from .env



  BASE_DIR: "D:/Documents/Italy/UNIPD/University Acadamico/TESI/project/rag_information_extractor"
  DATASET_TYPE: "TRAIN"                 ## one of: "TRAIN", "TEST"

  
  # Document ingestion
  READ_MODE: "single"
  PAGES_JOINING_STR: '------------------------------ THIS IS A CUSTOM END OF PAGE ------------------------------' #"-"*30 + " THIS IS A CUSTOM END OF PAGE " + "-"*30
  PDF_LOADER: "pymupdf" # ("pymupdf", "pypdf")
